tests: fix the rtsym scalar reading
Rtsym reports scalar values in little endian word order.
We need to reverse the words.  This fixes the basic netdev
unit test.

Traceback (most recent call last):
  File
"/home/bbslave/netro-test-infra.hg/ti/pymod/netro/testinfra/test.py", line
665, in run
    result = test.run()
  File "/home/bbslave/nfp-drv-kmods/tests/common_test.py", line 129, in run
    self.execute()
  File "/home/bbslave/nfp-drv-kmods/tests/unit/tests.py", line 745, in
execute
    raise NtiError("SR-IOV VF limit not reported")
NtiError: SR-IOV VF limit not reported
tests.unit.netdev                            : FAILED

Signed-off-by: Jakub Kicinski <jakub.kicinski@netronome.com>