nfp: use eth_hw_addr_set to set mac address
As of the following upstream commit, added to net-next for inclusion in
v5.17, the dev_addr field of netdev is const.

  adeef3e32146 ("net: constify netdev->dev_addr")

This results in a warning when passing this field to ether_addr_copy().

In upstream net-next, head commit 4f47d5d507d6 ("ipv4: Exposing
__ip_sock_set_tos() in ip.h"), ether_addr_copy expects its first argument.

  $ gcc --version
  gcc (Debian 8.3.0-6) 8.3.0
  Copyright (C) 2018 Free Software Foundation, Inc.
  This is free software; see the source for copying conditions.  There is NO
  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

  $ make
  ...
    CC [M]  /home/horms/projects/customers/corigine/nfp-drv-kmods/src/nfpcore/nfp_net_vnic.o
  ../../nfp-drv-kmods/src/nfpcore/nfp_net_vnic.c: In function ‘nfp_net_vnic_assign_addr’:
  ../../nfp-drv-kmods/src/nfpcore/nfp_net_vnic.c:560:24: error: passing argument 1 of ‘ether_addr_copy’ discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
    ether_addr_copy(netdev->dev_addr, mac_addr);
                    ~~~~~~^~~~~~~~~~
  In file included from ../../nfp-drv-kmods/src/nfpcore/nfp_net_vnic.c:16:
  ./include/linux/etherdevice.h:295:40: note: expected ‘u8 *’ {aka ‘unsigned char *’} but argument is of type ‘const unsigned char *’
   static inline void ether_addr_copy(u8 *dst, const u8 *src)

Resolve this problem by using eth_hw_addr_set() instead of
ether_addr_copy(), which is in keeping with upstream best practice
as of v5.16.

  e9637775c05f ("Merge branch 'hw_addr_set'")

Signed-off-by: Simon Horman <simon.horman@corigine.com>
Signed-off-by: Yinjun Zhang <yinjun.zhang@corigine.com>