tests: ebpf: fix codegen check on drv runs
A lot of ebpfdrv tests are currently failing because of what
looks like a mistake in the skip logic.  get_ext_source_name()
returns None for ebpfdrv run, but get_source_name() blindly
passes the result into os.path.isfile(), which (at least on
the California nightly test setup) results in:

Traceback (most recent call last):
File "/nfp-drv-kmods/nti/ti/pymod/netro/testinfra/test.py", line 651, in run
result = test.run()
File "/nfp-drv-kmods/tests/common_test.py", line 234, in run
self.execute()
File "/nfp-drv-kmods/tests/common_test.py", line 825, in execute
ret = self.install_filter()
File "/nfp-drv-kmods/tests/ebpf/xdp.py", line 137, in install_filter
self.jit_codegen.check(self.get_jit_patterns_file_name(), prog_id)
File "/nfp-drv-kmods/tests/ebpf/xdp.py", line 130, in get_jit_patterns_file_name
return self.jit_codegen.get_source_name(self)
File "/nfp-drv-kmods/tests/ebpf/jit_codegen_scan.py", line 145, in get_source_name
if not os.path.isfile(filename):
File "/usr/lib/python2.7/genericpath.py", line 37, in isfile
st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

Signed-off-by: Jakub Kicinski <jakub.kicinski@netronome.com>
Reviewed-by: Jiong Wang <jiong.wang@netronome.com>