tests: ebpf: don't include ASSEMBLY unaware header files in .S
It is unsafe to include ASSEMBLY unaware header files in .S. This is
because .S does support preprocessing, but all processed contents will be
fed to assembler parser which only understands asm syntax, not any of those
C types, functions and variables declarations.

Normally, if one header file is supposed to be included by both assembly
and C files, those parts that are supposed to be exposed to assembly will
be gated by "#ifdef ASSEMBLY".

In our tests/samples/, we want the value of macro TC_ACT_SHOT, it is
defined inside uapi/linux/pkt_cls.h and has not considered to be included
by assembly file. So, we can't include pkt_cls.h inside .S, otherwise we
will end up with errors like:

  .../asm-generic/int-ll64.h:20:1: error: invalid register/token name
  typedef __signed__ char __s8;
  ^
  .../asm-generic/int-ll64.h:21:1: error: invalid register/token name

This error should have been noticed since we included pkt_cls.h in these .S
files, however there was a BPF LLVM assembler bug which caused the
assembler silently ignoring parser failures. This bug has been fixed by
r329849:
  https://marc.info/?l=llvm-commits&m=152347847309118&w=2
  bpf: signal error instead of silent drop for certain invalid asm insn

And the fix has been included since LLVM release 7.0.

This patch just hard code the value of TC_ACT_SHOT inside the code, the
value is uapi so is unlikely to be changed.

v2:
  - Fix grammar by dropping a "to". (Quentin)

Signed-off-by: Jiong Wang <jiong.wang@netronome.com>
Reviewed-by: Quentin Monnet <quentin.monnet@netronome.com>
Reviewed-by: Jakub Kicinski <jakub.kicinski@netronome.com>