workflow: add builds against Ubuntu-22.04
Add build against Ubuntu-22.04 in OOT driver build workflow.
HWE kernels for 22.04 not have been released, so don't include builds
for them.

There was, for a time at least, 5.15.0-35.36+22.10.1 linux-headers packages
present in the pool/directory. These clashed with the
5.15.0-35.36 packages; could not be build without modifying the 22.04
job, without modifying the job, due to a compiler version missmatch; and
caused the error error below. A reject match is added to void similar
situations by skipping download of such header packages.

  Error: warning: the compiler differs from the one used to build the kernel.

Signed-off-by: Yu Xiao <yu.xiao@corigine.com>
Signed-off-by: Simon Horman <simon.horman@corigine.com>
Signed-off-by: Louis Peens <louis.peens@corigine.com>